/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QaRouteImport } from './routes/qa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaIndexRouteImport } from './routes/qa.index'
import { Route as QaIdRouteImport } from './routes/qa.$id'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardUiSettingsRouteImport } from './routes/_authenticated/dashboard.ui-settings'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard.reports'
import { Route as AuthenticatedDashboardQuestionsRouteImport } from './routes/_authenticated/dashboard.questions'
import { Route as AuthenticatedDashboardPublicContentRouteImport } from './routes/_authenticated/dashboard.public-content'
import { Route as AuthenticatedDashboardPoolRouteImport } from './routes/_authenticated/dashboard.pool'
import { Route as AuthenticatedDashboardPeerReviewRouteImport } from './routes/_authenticated/dashboard.peer-review'
import { Route as AuthenticatedDashboardMyAnswersRouteImport } from './routes/_authenticated/dashboard.my-answers'
import { Route as AuthenticatedDashboardMosquesRouteImport } from './routes/_authenticated/dashboard.mosques'
import { Route as AuthenticatedDashboardMosqueAdminRouteImport } from './routes/_authenticated/dashboard.mosque-admin'
import { Route as AuthenticatedDashboardManageShaykhsRouteImport } from './routes/_authenticated/dashboard.manage-shaykhs'
import { Route as AuthenticatedDashboardLibraryRouteImport } from './routes/_authenticated/dashboard.library'
import { Route as AuthenticatedDashboardCreateShaykhRouteImport } from './routes/_authenticated/dashboard.create-shaykh'
import { Route as AuthenticatedDashboardCreateAdminRouteImport } from './routes/_authenticated/dashboard.create-admin'
import { Route as AuthenticatedDashboardCategoriesRouteImport } from './routes/_authenticated/dashboard.categories'
import { Route as AuthenticatedDashboardAskRouteImport } from './routes/_authenticated/dashboard.ask'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardQuestionsIndexRouteImport } from './routes/_authenticated/dashboard.questions.index'
import { Route as AuthenticatedDashboardQuestionsIdRouteImport } from './routes/_authenticated/dashboard.questions.$id'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIndexRoute = QaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QaRoute,
} as any)
const QaIdRoute = QaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QaRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUiSettingsRoute =
  AuthenticatedDashboardUiSettingsRouteImport.update({
    id: '/ui-settings',
    path: '/ui-settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardQuestionsRoute =
  AuthenticatedDashboardQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPublicContentRoute =
  AuthenticatedDashboardPublicContentRouteImport.update({
    id: '/public-content',
    path: '/public-content',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPoolRoute =
  AuthenticatedDashboardPoolRouteImport.update({
    id: '/pool',
    path: '/pool',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPeerReviewRoute =
  AuthenticatedDashboardPeerReviewRouteImport.update({
    id: '/peer-review',
    path: '/peer-review',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyAnswersRoute =
  AuthenticatedDashboardMyAnswersRouteImport.update({
    id: '/my-answers',
    path: '/my-answers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMosquesRoute =
  AuthenticatedDashboardMosquesRouteImport.update({
    id: '/mosques',
    path: '/mosques',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMosqueAdminRoute =
  AuthenticatedDashboardMosqueAdminRouteImport.update({
    id: '/mosque-admin',
    path: '/mosque-admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardManageShaykhsRoute =
  AuthenticatedDashboardManageShaykhsRouteImport.update({
    id: '/manage-shaykhs',
    path: '/manage-shaykhs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLibraryRoute =
  AuthenticatedDashboardLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCreateShaykhRoute =
  AuthenticatedDashboardCreateShaykhRouteImport.update({
    id: '/create-shaykh',
    path: '/create-shaykh',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCreateAdminRoute =
  AuthenticatedDashboardCreateAdminRouteImport.update({
    id: '/create-admin',
    path: '/create-admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCategoriesRoute =
  AuthenticatedDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAskRoute =
  AuthenticatedDashboardAskRouteImport.update({
    id: '/ask',
    path: '/ask',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardQuestionsIndexRoute =
  AuthenticatedDashboardQuestionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardQuestionsRoute,
  } as any)
const AuthenticatedDashboardQuestionsIdRoute =
  AuthenticatedDashboardQuestionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardQuestionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qa': typeof QaRouteWithChildren
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/qa/$id': typeof QaIdRoute
  '/qa/': typeof QaIndexRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/ask': typeof AuthenticatedDashboardAskRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/create-admin': typeof AuthenticatedDashboardCreateAdminRoute
  '/dashboard/create-shaykh': typeof AuthenticatedDashboardCreateShaykhRoute
  '/dashboard/library': typeof AuthenticatedDashboardLibraryRoute
  '/dashboard/manage-shaykhs': typeof AuthenticatedDashboardManageShaykhsRoute
  '/dashboard/mosque-admin': typeof AuthenticatedDashboardMosqueAdminRoute
  '/dashboard/mosques': typeof AuthenticatedDashboardMosquesRoute
  '/dashboard/my-answers': typeof AuthenticatedDashboardMyAnswersRoute
  '/dashboard/peer-review': typeof AuthenticatedDashboardPeerReviewRoute
  '/dashboard/pool': typeof AuthenticatedDashboardPoolRoute
  '/dashboard/public-content': typeof AuthenticatedDashboardPublicContentRoute
  '/dashboard/questions': typeof AuthenticatedDashboardQuestionsRouteWithChildren
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/ui-settings': typeof AuthenticatedDashboardUiSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/questions/$id': typeof AuthenticatedDashboardQuestionsIdRoute
  '/dashboard/questions/': typeof AuthenticatedDashboardQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/qa/$id': typeof QaIdRoute
  '/qa': typeof QaIndexRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/ask': typeof AuthenticatedDashboardAskRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/create-admin': typeof AuthenticatedDashboardCreateAdminRoute
  '/dashboard/create-shaykh': typeof AuthenticatedDashboardCreateShaykhRoute
  '/dashboard/library': typeof AuthenticatedDashboardLibraryRoute
  '/dashboard/manage-shaykhs': typeof AuthenticatedDashboardManageShaykhsRoute
  '/dashboard/mosque-admin': typeof AuthenticatedDashboardMosqueAdminRoute
  '/dashboard/mosques': typeof AuthenticatedDashboardMosquesRoute
  '/dashboard/my-answers': typeof AuthenticatedDashboardMyAnswersRoute
  '/dashboard/peer-review': typeof AuthenticatedDashboardPeerReviewRoute
  '/dashboard/pool': typeof AuthenticatedDashboardPoolRoute
  '/dashboard/public-content': typeof AuthenticatedDashboardPublicContentRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/ui-settings': typeof AuthenticatedDashboardUiSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/questions/$id': typeof AuthenticatedDashboardQuestionsIdRoute
  '/dashboard/questions': typeof AuthenticatedDashboardQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/qa': typeof QaRouteWithChildren
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/qa/$id': typeof QaIdRoute
  '/qa/': typeof QaIndexRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/ask': typeof AuthenticatedDashboardAskRoute
  '/_authenticated/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/_authenticated/dashboard/create-admin': typeof AuthenticatedDashboardCreateAdminRoute
  '/_authenticated/dashboard/create-shaykh': typeof AuthenticatedDashboardCreateShaykhRoute
  '/_authenticated/dashboard/library': typeof AuthenticatedDashboardLibraryRoute
  '/_authenticated/dashboard/manage-shaykhs': typeof AuthenticatedDashboardManageShaykhsRoute
  '/_authenticated/dashboard/mosque-admin': typeof AuthenticatedDashboardMosqueAdminRoute
  '/_authenticated/dashboard/mosques': typeof AuthenticatedDashboardMosquesRoute
  '/_authenticated/dashboard/my-answers': typeof AuthenticatedDashboardMyAnswersRoute
  '/_authenticated/dashboard/peer-review': typeof AuthenticatedDashboardPeerReviewRoute
  '/_authenticated/dashboard/pool': typeof AuthenticatedDashboardPoolRoute
  '/_authenticated/dashboard/public-content': typeof AuthenticatedDashboardPublicContentRoute
  '/_authenticated/dashboard/questions': typeof AuthenticatedDashboardQuestionsRouteWithChildren
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/ui-settings': typeof AuthenticatedDashboardUiSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/questions/$id': typeof AuthenticatedDashboardQuestionsIdRoute
  '/_authenticated/dashboard/questions/': typeof AuthenticatedDashboardQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/qa'
    | '/signup'
    | '/verify-otp'
    | '/dashboard'
    | '/qa/$id'
    | '/qa/'
    | '/dashboard/admin'
    | '/dashboard/ask'
    | '/dashboard/categories'
    | '/dashboard/create-admin'
    | '/dashboard/create-shaykh'
    | '/dashboard/library'
    | '/dashboard/manage-shaykhs'
    | '/dashboard/mosque-admin'
    | '/dashboard/mosques'
    | '/dashboard/my-answers'
    | '/dashboard/peer-review'
    | '/dashboard/pool'
    | '/dashboard/public-content'
    | '/dashboard/questions'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/ui-settings'
    | '/dashboard/'
    | '/dashboard/questions/$id'
    | '/dashboard/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/verify-otp'
    | '/qa/$id'
    | '/qa'
    | '/dashboard/admin'
    | '/dashboard/ask'
    | '/dashboard/categories'
    | '/dashboard/create-admin'
    | '/dashboard/create-shaykh'
    | '/dashboard/library'
    | '/dashboard/manage-shaykhs'
    | '/dashboard/mosque-admin'
    | '/dashboard/mosques'
    | '/dashboard/my-answers'
    | '/dashboard/peer-review'
    | '/dashboard/pool'
    | '/dashboard/public-content'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/ui-settings'
    | '/dashboard'
    | '/dashboard/questions/$id'
    | '/dashboard/questions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/qa'
    | '/signup'
    | '/verify-otp'
    | '/_authenticated/dashboard'
    | '/qa/$id'
    | '/qa/'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/ask'
    | '/_authenticated/dashboard/categories'
    | '/_authenticated/dashboard/create-admin'
    | '/_authenticated/dashboard/create-shaykh'
    | '/_authenticated/dashboard/library'
    | '/_authenticated/dashboard/manage-shaykhs'
    | '/_authenticated/dashboard/mosque-admin'
    | '/_authenticated/dashboard/mosques'
    | '/_authenticated/dashboard/my-answers'
    | '/_authenticated/dashboard/peer-review'
    | '/_authenticated/dashboard/pool'
    | '/_authenticated/dashboard/public-content'
    | '/_authenticated/dashboard/questions'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/ui-settings'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/questions/$id'
    | '/_authenticated/dashboard/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  QaRoute: typeof QaRouteWithChildren
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/': {
      id: '/qa/'
      path: '/'
      fullPath: '/qa/'
      preLoaderRoute: typeof QaIndexRouteImport
      parentRoute: typeof QaRoute
    }
    '/qa/$id': {
      id: '/qa/$id'
      path: '/$id'
      fullPath: '/qa/$id'
      preLoaderRoute: typeof QaIdRouteImport
      parentRoute: typeof QaRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ui-settings': {
      id: '/_authenticated/dashboard/ui-settings'
      path: '/ui-settings'
      fullPath: '/dashboard/ui-settings'
      preLoaderRoute: typeof AuthenticatedDashboardUiSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/questions': {
      id: '/_authenticated/dashboard/questions'
      path: '/questions'
      fullPath: '/dashboard/questions'
      preLoaderRoute: typeof AuthenticatedDashboardQuestionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/public-content': {
      id: '/_authenticated/dashboard/public-content'
      path: '/public-content'
      fullPath: '/dashboard/public-content'
      preLoaderRoute: typeof AuthenticatedDashboardPublicContentRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/pool': {
      id: '/_authenticated/dashboard/pool'
      path: '/pool'
      fullPath: '/dashboard/pool'
      preLoaderRoute: typeof AuthenticatedDashboardPoolRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/peer-review': {
      id: '/_authenticated/dashboard/peer-review'
      path: '/peer-review'
      fullPath: '/dashboard/peer-review'
      preLoaderRoute: typeof AuthenticatedDashboardPeerReviewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-answers': {
      id: '/_authenticated/dashboard/my-answers'
      path: '/my-answers'
      fullPath: '/dashboard/my-answers'
      preLoaderRoute: typeof AuthenticatedDashboardMyAnswersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/mosques': {
      id: '/_authenticated/dashboard/mosques'
      path: '/mosques'
      fullPath: '/dashboard/mosques'
      preLoaderRoute: typeof AuthenticatedDashboardMosquesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/mosque-admin': {
      id: '/_authenticated/dashboard/mosque-admin'
      path: '/mosque-admin'
      fullPath: '/dashboard/mosque-admin'
      preLoaderRoute: typeof AuthenticatedDashboardMosqueAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/manage-shaykhs': {
      id: '/_authenticated/dashboard/manage-shaykhs'
      path: '/manage-shaykhs'
      fullPath: '/dashboard/manage-shaykhs'
      preLoaderRoute: typeof AuthenticatedDashboardManageShaykhsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/library': {
      id: '/_authenticated/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof AuthenticatedDashboardLibraryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/create-shaykh': {
      id: '/_authenticated/dashboard/create-shaykh'
      path: '/create-shaykh'
      fullPath: '/dashboard/create-shaykh'
      preLoaderRoute: typeof AuthenticatedDashboardCreateShaykhRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/create-admin': {
      id: '/_authenticated/dashboard/create-admin'
      path: '/create-admin'
      fullPath: '/dashboard/create-admin'
      preLoaderRoute: typeof AuthenticatedDashboardCreateAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/categories': {
      id: '/_authenticated/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ask': {
      id: '/_authenticated/dashboard/ask'
      path: '/ask'
      fullPath: '/dashboard/ask'
      preLoaderRoute: typeof AuthenticatedDashboardAskRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/questions/': {
      id: '/_authenticated/dashboard/questions/'
      path: '/'
      fullPath: '/dashboard/questions/'
      preLoaderRoute: typeof AuthenticatedDashboardQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardQuestionsRoute
    }
    '/_authenticated/dashboard/questions/$id': {
      id: '/_authenticated/dashboard/questions/$id'
      path: '/$id'
      fullPath: '/dashboard/questions/$id'
      preLoaderRoute: typeof AuthenticatedDashboardQuestionsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardQuestionsRoute
    }
  }
}

interface AuthenticatedDashboardQuestionsRouteChildren {
  AuthenticatedDashboardQuestionsIdRoute: typeof AuthenticatedDashboardQuestionsIdRoute
  AuthenticatedDashboardQuestionsIndexRoute: typeof AuthenticatedDashboardQuestionsIndexRoute
}

const AuthenticatedDashboardQuestionsRouteChildren: AuthenticatedDashboardQuestionsRouteChildren =
  {
    AuthenticatedDashboardQuestionsIdRoute:
      AuthenticatedDashboardQuestionsIdRoute,
    AuthenticatedDashboardQuestionsIndexRoute:
      AuthenticatedDashboardQuestionsIndexRoute,
  }

const AuthenticatedDashboardQuestionsRouteWithChildren =
  AuthenticatedDashboardQuestionsRoute._addFileChildren(
    AuthenticatedDashboardQuestionsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardAskRoute: typeof AuthenticatedDashboardAskRoute
  AuthenticatedDashboardCategoriesRoute: typeof AuthenticatedDashboardCategoriesRoute
  AuthenticatedDashboardCreateAdminRoute: typeof AuthenticatedDashboardCreateAdminRoute
  AuthenticatedDashboardCreateShaykhRoute: typeof AuthenticatedDashboardCreateShaykhRoute
  AuthenticatedDashboardLibraryRoute: typeof AuthenticatedDashboardLibraryRoute
  AuthenticatedDashboardManageShaykhsRoute: typeof AuthenticatedDashboardManageShaykhsRoute
  AuthenticatedDashboardMosqueAdminRoute: typeof AuthenticatedDashboardMosqueAdminRoute
  AuthenticatedDashboardMosquesRoute: typeof AuthenticatedDashboardMosquesRoute
  AuthenticatedDashboardMyAnswersRoute: typeof AuthenticatedDashboardMyAnswersRoute
  AuthenticatedDashboardPeerReviewRoute: typeof AuthenticatedDashboardPeerReviewRoute
  AuthenticatedDashboardPoolRoute: typeof AuthenticatedDashboardPoolRoute
  AuthenticatedDashboardPublicContentRoute: typeof AuthenticatedDashboardPublicContentRoute
  AuthenticatedDashboardQuestionsRoute: typeof AuthenticatedDashboardQuestionsRouteWithChildren
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardUiSettingsRoute: typeof AuthenticatedDashboardUiSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardAskRoute: AuthenticatedDashboardAskRoute,
    AuthenticatedDashboardCategoriesRoute:
      AuthenticatedDashboardCategoriesRoute,
    AuthenticatedDashboardCreateAdminRoute:
      AuthenticatedDashboardCreateAdminRoute,
    AuthenticatedDashboardCreateShaykhRoute:
      AuthenticatedDashboardCreateShaykhRoute,
    AuthenticatedDashboardLibraryRoute: AuthenticatedDashboardLibraryRoute,
    AuthenticatedDashboardManageShaykhsRoute:
      AuthenticatedDashboardManageShaykhsRoute,
    AuthenticatedDashboardMosqueAdminRoute:
      AuthenticatedDashboardMosqueAdminRoute,
    AuthenticatedDashboardMosquesRoute: AuthenticatedDashboardMosquesRoute,
    AuthenticatedDashboardMyAnswersRoute: AuthenticatedDashboardMyAnswersRoute,
    AuthenticatedDashboardPeerReviewRoute:
      AuthenticatedDashboardPeerReviewRoute,
    AuthenticatedDashboardPoolRoute: AuthenticatedDashboardPoolRoute,
    AuthenticatedDashboardPublicContentRoute:
      AuthenticatedDashboardPublicContentRoute,
    AuthenticatedDashboardQuestionsRoute:
      AuthenticatedDashboardQuestionsRouteWithChildren,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardUiSettingsRoute:
      AuthenticatedDashboardUiSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface QaRouteChildren {
  QaIdRoute: typeof QaIdRoute
  QaIndexRoute: typeof QaIndexRoute
}

const QaRouteChildren: QaRouteChildren = {
  QaIdRoute: QaIdRoute,
  QaIndexRoute: QaIndexRoute,
}

const QaRouteWithChildren = QaRoute._addFileChildren(QaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  QaRoute: QaRouteWithChildren,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
