/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QaRouteImport } from './routes/qa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaIndexRouteImport } from './routes/qa.index'
import { Route as QaIdRouteImport } from './routes/qa.$id'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIndexRoute = QaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QaRoute,
} as any)
const QaIdRoute = QaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qa': typeof QaRouteWithChildren
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/qa/$id': typeof QaIdRoute
  '/qa/': typeof QaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/qa/$id': typeof QaIdRoute
  '/qa': typeof QaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qa': typeof QaRouteWithChildren
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/qa/$id': typeof QaIdRoute
  '/qa/': typeof QaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/qa'
    | '/signup'
    | '/verify-otp'
    | '/qa/$id'
    | '/qa/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/verify-otp' | '/qa/$id' | '/qa'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/qa'
    | '/signup'
    | '/verify-otp'
    | '/qa/$id'
    | '/qa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  QaRoute: typeof QaRouteWithChildren
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/': {
      id: '/qa/'
      path: '/'
      fullPath: '/qa/'
      preLoaderRoute: typeof QaIndexRouteImport
      parentRoute: typeof QaRoute
    }
    '/qa/$id': {
      id: '/qa/$id'
      path: '/$id'
      fullPath: '/qa/$id'
      preLoaderRoute: typeof QaIdRouteImport
      parentRoute: typeof QaRoute
    }
  }
}

interface QaRouteChildren {
  QaIdRoute: typeof QaIdRoute
  QaIndexRoute: typeof QaIndexRoute
}

const QaRouteChildren: QaRouteChildren = {
  QaIdRoute: QaIdRoute,
  QaIndexRoute: QaIndexRoute,
}

const QaRouteWithChildren = QaRoute._addFileChildren(QaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  QaRoute: QaRouteWithChildren,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
